### PR TITLE
Fix reference link

### PR DESCRIPTION
**Pull request by blossomica**
I noticed the reference link is not functioning, so I substituted it with one that works (I found it online so if it is not the right one you can let me know). 

There is another link as well that is not functioning towards the end of the README file,but I am not sure what is the right substitution for it so I left it as is.  If you can link me to the right alternative I can add that too.

### CODE REVIEW

**Comment by agarie** [comment]
What is the other link not working? Thanks for the PR!

**Comment by blossomica** [comment]
@agarie - This one http://rubyforge.org/projects/rb-gsl/

**Comment by agarie** [comment]
Rubyforge is down, apparently. I *think* that a better link would be [rubygems.org/gems/rb-gsl](https://rubygems.org/gems/rb-gsl).

**Comment by blossomica** [comment]
@agarie - to substitute the link that points here "If you encounter bugs in Ruby/GSL, please e-mail to me, or submit reports from http://rubyforge.org/projects/rb-gsl/."? Also is the reference link I changed okay? Once I know all that and get the go ahead I will fix the other links too. Thanks for the guidance.

**Comment by agarie** [comment]
The link you changed (the reference, i.e. `ref_rdoc.html`) is alright IMO.

Err, I was wrong, that link is the project page of rb-gsl on rubyforge. So it should be changed to this project in GitHub, i.e. [http://rubyforge.org/projects/rb-gsl/](http://rubyforge.org/projects/rb-gsl/) -> [https://github.com/SciRuby/rb-gsl](https://github.com/SciRuby/rb-gsl). Does that make sense? :)

**Comment by blossomica** [comment]
That makes sense but I thought it was obvious if they are reading the README from github lol. Anyways I should use that link right?

**Comment by agarie** [comment]
Not if they're reading from a local copy or from the code downloaded via `gem install`. :)

**Comment by blossomica** [comment]
@agarie - You are absolutely right. I forgot about that part, thanks for reminding me. I have updated the PR.

**Comment by minad** [comment]
fixed in the readme?

**Comment by blossomica** [comment]
Yes it seems it got fixed after I submitted my PR.  It all works perfect now. @minad

**Pull request closed without merging**
